apiVersion: v1
kind: Pod
metadata:
  name: photos
spec:
  containers:
    - name: photos
      image: heavydistortion/bookworm-photos
      ports:
        - containerPort: 8080
          hostPort: 8080
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: photos-service
  namespace: default
spec:
  type: NodePort
  selector:
    photos: web
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 8080