apiVersion: apps/v1
kind: Deployment
metadata:
  name: photos
  namespace: default
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  selector:
    matchLabels:
      photos: web
  template:
    metadata:
      labels:
        photos: web
    spec:
      containers:
        - name: photos
          image: heavydistortion/bookworm-photos:latest
          ports:
            - containerPort: 8080
      terminationGracePeriodSeconds: 10